"""NebulonMind API package.

* ``client.py`` — HTTP client for the NebulonDB REST API (backend channel).
* ``schemas.py`` — request/response models for every endpoint (Phase 4.1).
* ``errors.py`` — standard error envelope (Phase 4.7).
* ``service.py`` — per-user service bundles + injectable service providers (4.2/4.12; distinct from the Step 2 LLM providers in ``intelligence/providers.py``).
* ``server.py`` — ``create_app()``, the NebulonMind service itself (port 9696).
"""

from .client import NebulonDBClient, NebulonDBError
from .errors import error_response, register_exception_handlers
from .schemas import (
    AgentSessionCreate,
    AgentSessionData,
    AgentSessionEnvelope,
    AgentSessionListData,
    AgentSessionListEnvelope,
    BackgroundAgentEnvelope,
    BackgroundAgentReport,
    BackgroundJobStatus,
    BackgroundMemoryRunRequest,
    BackgroundSchedulerStatus,
    BackgroundStatusEnvelope,
    BackgroundTaskRunRequest,
    ContextData,
    ContextEnvelope,
    DecideData,
    DecideEnvelope,
    DeleteData,
    DeleteEnvelope,
    Envelope,
    HealthData,
    HealthEnvelope,
    IngestReport,
    IntelligenceDecideRequest,
    IntelligenceInput,
    IntelligenceProcessRequest,
    MemoryCreate,
    MemoryData,
    MemoryEnvelope,
    MemoryUpdate,
    ProcessData,
    ProcessEnvelope,
    RelateData,
    RelateEnvelope,
    SearchData,
    SearchEnvelope,
    UserCreateRequest,
    UserData,
    UserEnvelope,
)
from .service import (
    DefaultServiceProvider,
    InMemoryServiceProvider,
    ServiceBundle,
    ServiceProvider,
)
from .server import create_app

__all__ = [
    "AgentSessionCreate",
    "AgentSessionData",
    "AgentSessionEnvelope",
    "AgentSessionListData",
    "AgentSessionListEnvelope",
    "BackgroundAgentEnvelope",
    "BackgroundAgentReport",
    "BackgroundJobStatus",
    "BackgroundMemoryRunRequest",
    "BackgroundSchedulerStatus",
    "BackgroundStatusEnvelope",
    "BackgroundTaskRunRequest",
    "ContextData",
    "ContextEnvelope",
    "DecideData",
    "DecideEnvelope",
    "DefaultServiceProvider",
    "DeleteData",
    "DeleteEnvelope",
    "Envelope",
    "HealthData",
    "HealthEnvelope",
    "InMemoryServiceProvider",
    "IngestReport",
    "IntelligenceDecideRequest",
    "IntelligenceInput",
    "IntelligenceProcessRequest",
    "MemoryCreate",
    "MemoryData",
    "MemoryEnvelope",
    "MemoryUpdate",
    "NebulonDBClient",
    "NebulonDBError",
    "ProcessData",
    "ProcessEnvelope",
    "RelateData",
    "RelateEnvelope",
    "SearchData",
    "SearchEnvelope",
    "ServiceBundle",
    "ServiceProvider",
    "UserCreateRequest",
    "UserData",
    "UserEnvelope",
    "create_app",
    "error_response",
    "register_exception_handlers",
]